### ISSUE TITLE
`Unexpected identifier`, when testing with jest and enzyme

### ISSUE THREAD

**Issue by relaxomatic** [volkov97/react-compound-timer#11]
When running my tests, when I mount a component that uses compound timer to take a snapshot I get this error. Using v1.0.13
```
...\node_modules\react-compound-timer\build\components\Timer\Timer.js:25`
    import React from 'react';
           ^^^^^

    SyntaxError: Unexpected identifier
```

**Comment by myThorsten** [comment]
I'm having the same issue. 

To reproduce:
1. run **create-react-app** for a fresh, untainted start
2. run **npm test** to verify that it is not failing
3. install **react-compound-timer** and import it into _App.js_
4. run **npm test** again and receive the mentioned error

![image](https://user-images.githubusercontent.com/9773490/59690914-7e5a6300-91e2-11e9-88ae-d3de7385e397.png)

**Comment by kousu** [comment]
I hit this too and just spent about 4 hours digging around in javascript to figure out the issue. The problem is that node not support the ES6 `import`/`export` syntax: as of april 2019 https://stackoverflow.com/a/37132668

> [Latest NodeJS](https://nodejs.org/api/esm.html#esm_ecmascript_modules) still lists ES Modules as experimental, behind a flag.

The answer is here: https://stackoverflow.com/a/35171227

> Then compile your TypeScript with --module commonjs.

but if you look in `tsconfig.json` you see;

>     "module": "esnext",
--

My app runs fine *under Electron* with this timer imported. I wonder if @volkov97 is using that, or Chrome, as their platform for testing stuff, and if that does support ES6 imports. That would explain why this is only showing up under testing: jest uses node.
